#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Render a terminal-style figure card from a committed text source.

    python scripts/render_terminal_card.py week-20-.../docs/blog/figures/05-cloudtrail-record.card

Why this exists (2026-09-26)
----------------------------
Three Week 20 figures -- the CloudTrail record, the event that matched nothing,
and the replay proof -- were typeset by hand and their sources thrown away. Jay
asked what one of them was and where it came from, and the only honest answer
was "a card I rendered, from data I no longer have in any committed form."

That is exactly the failure render_card.py was written for after Week 16: a card
generated ad hoc, the source discarded, and nothing to re-export when it needed
changing. The LinkedIn card has committed HTML for that reason. The figure cards
did not, and the data behind the CloudTrail one lives in an S3 bucket that
teardown deletes.

A figure whose source is gone is a claim you can no longer check or correct.

THE FORMAT
    title:    one line, bold, above the frame
    subtitle: one line, grey, under the title
    width:    optional CSS pixels (default 1100)
    ---
    everything below is the body, rendered verbatim in a monospace frame

Body lines beginning with '#' render dimmed, as comments. Nothing else is
interpreted -- the point is to reproduce captured output exactly, so the
renderer must not reformat it.
"""
import argparse
import html
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]

TEMPLATE = """<!doctype html>
<!-- GENERATED by scripts/render_terminal_card.py from %(srcname)s -- edit the
     .card source, never this file. -->
<meta charset="utf-8">
<style>
  * { box-sizing: border-box }
  html, body { margin: 0; padding: 0; background: #fff }
  body { width: %(width)spx; color: #16191f;
         font-family: "Segoe UI", -apple-system, "Helvetica Neue", Arial, sans-serif;
         -webkit-font-smoothing: antialiased }
  .wrap { padding: 26px 30px 28px }
  h1 { font-size: 21px; font-weight: 600; margin: 0; letter-spacing: -.01em }
  .sub { font-size: 13px; color: #6c757d; margin-top: 6px }
  pre { margin: 18px 0 0; background: #1f2937; color: #e6eaf0; border-radius: 10px;
        padding: 22px 26px; font-size: 14px; line-height: 1.55; overflow: visible;
        font-family: "Cascadia Mono", "SF Mono", Consolas, "Liberation Mono", monospace;
        white-space: pre; tab-size: 4 }
  .c  { color: #97a3b6 }
  .ok { color: #7ee2a8 }
  .no { color: #ff8a8a }
  .br { color: #ffc46b }
</style>
<div class="wrap">
  <h1>%(title)s</h1>
  <div class="sub">%(subtitle)s</div>
  <pre>%(body)s</pre>
</div>
"""


def parse(path):
    raw = path.read_text(encoding="utf-8")
    if "\n---\n" not in raw:
        sys.exit("%s: no '---' separating the header from the body" % path.name)
    head, body = raw.split("\n---\n", 1)
    meta = {}
    for line in head.splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            meta[k.strip().lower()] = v.strip()
    for required in ("title", "subtitle"):
        if required not in meta:
            sys.exit("%s: missing '%s:' in the header" % (path.name, required))
    return meta, body.rstrip("\n")


# The three outcomes prove_unmatched.sh and prove_replay.sh actually emit.
# BROKEN is its own colour on purpose: it means a precondition did not hold,
# so the check never ran, and colouring it like a failure or like a pass
# would both be wrong.
MARKERS = (("[ok]", "ok"), ("[FAIL]", "no"), ("[BROKEN]", "br"))


def render_body(body):
    out = []
    for line in body.split(chr(10)):
        esc = html.escape(line)
        stripped = line.lstrip()
        # A comment is dimmed. Detected on the raw line so indentation is
        # preserved exactly -- these cards show captured output, and
        # re-indenting it would make them a paraphrase.
        if stripped.startswith("#"):
            out.append('<span class="c">%s</span>' % esc)
            continue
        cls = next((c for m, c in MARKERS if stripped.startswith(m)), None)
        out.append('<span class="%s">%s</span>' % (cls, esc) if cls else esc)
    return chr(10).join(out)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("source", help="path to a .card file")
    ap.add_argument("--scale", type=int, default=2)
    ap.add_argument("--out", default=None,
                    help="PNG path (default: sibling .png of the source name)")
    args = ap.parse_args()

    src = pathlib.Path(args.source)
    if not src.is_absolute():
        src = REPO / src
    if not src.exists():
        sys.exit("no such source: %s" % src)

    meta, body = parse(src)
    width = int(meta.get("width", 1100))
    page_html = TEMPLATE % {
        "srcname": src.name,
        "width": width,
        "title": html.escape(meta["title"]),
        "subtitle": html.escape(meta["subtitle"]),
        "body": render_body(body),
    }
    tmp = src.with_suffix(".html")
    tmp.write_text(page_html, encoding="utf-8")

    out = pathlib.Path(args.out) if args.out else src.with_suffix(".png")
    if not out.is_absolute():
        out = REPO / out

    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        sys.exit("playwright is not installed")

    with sync_playwright() as p:
        b = p.chromium.launch()
        page = b.new_page(viewport={"width": width, "height": 800},
                          device_scale_factor=args.scale)
        page.goto(tmp.as_uri())
        page.wait_for_timeout(400)
        # full_page so the frame is never clipped: these cards vary in height
        # with their content, and a fixed viewport would silently cut the last
        # lines off the longest ones.
        page.screenshot(path=str(out), full_page=True)
        b.close()

    try:
        from PIL import Image
        print("wrote %s at %sx%s" % (out.name, *Image.open(out).size))
    except ImportError:
        print("wrote %s" % out.name)
    return 0


if __name__ == "__main__":
    sys.exit(main())
